export const sample_foods = [
  {
    id: "1",
    name: "Chicken Biryani",
    cookTime: "30-40",
    price: 300,
    favorite: true,
    origins: ["UAE"],
    stars: 4,
    imageUrl: "cbiryani.jpg",
    tags: ["Lunch", "Slowfood"],
  },
  {
    id: "2",
    name: "Pilau",
    cookTime: "30-40",
    price: 255,
    favorite: false,
    origins: ["UAE"],
    stars: 4.5,
    imageUrl: "pilau.jpg",
    tags: ["Lunch", "Slowfood"],
  },
  {
    id: "3",
    name: "Fries",
    cookTime: "30-40",
    price: 150,
    favorite: false,
    origins: ["UAE", "Kenya"],
    stars: 3.5,
    imageUrl: "fries.jpg",
    tags: ["Pizza"],
  },
  {
    id: "4",
    name: "Pizza",
    cookTime: "30-45",
    price: 1200,
    favorite: false,
    origins: ["UAE"],
    stars: 3.5,
    imageUrl: "pizza.jpeg",
    tags: ["Lunch", "Slowfood", "Pizza"],
  },
  {
    id: "5",
    name: "Spaghetti Bolognaise",
    cookTime: "30-40",
    price: 750,
    favorite: true,
    origins: ["Italy", "France"],
    stars: 5,
    imageUrl: "spagbolo.jpg",
    tags: ["Lunch", "Fastfood", "Pizza"],
  },
];

export const sample_tags = [
  { name: "All", count: 5 },
  { name: "Slowfood", count: 3 },
  { name: "Pizza", count: 2 },
  { name: "Lunch", count: 3 },
  { name: "Fastfood", count: 1 },
];

export const sample_users = [
  {
    id: 1,
    name: "mtu HALF",
    email: "mtuhalf@leats.com",
    password: "87654321",
    address: "Msa",
    isAdmin: false,
  },
  {
    id: 2,
    name: "localhost",
    email: "lhost@leats.com",
    password: "admin",
    address: "Msa",
    isAdmin: true,
  },
];
